//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string SKU { get; set; }
        public string Fert { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string NumeroDeSerie { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tipo Tipo1 { get; set; }
    }
}
